[[plugins]]
repo = 'kyazdani42/nvim-web-devicons'
on_event = 'BufEnter'

[[plugins]]
repo = 'kyazdani42/nvim-tree.lua'
on_event = 'BufEnter'
hook_source = '''
lua << EOF
-- examples for your init.lua

-- disable netrw at the very start of your init.lua (strongly advised)
vim.g.loaded = 1
vim.g.loaded_netrwPlugin = 1

-- setup with some options
require("nvim-tree").setup({
  sort_by = "case_sensitive",
  view = {
    adaptive_size = true,
    width = 50,
    mappings = {
      list = {
        { key = "u", action = "dir_up" },
      },
    },
  },
  renderer = {
    group_empty = true,
  },
  filters = {
    dotfiles = true,
  },
})
EOF

nnoremap <A-b> <Cmd>NvimTreeToggle<CR>
'''

[[plugins]]
repo = 'sidebar-nvim/sidebar.nvim'
on_event = 'BufEnter'
hook_source = '''
lua << EOF
require("sidebar-nvim").setup({
    disable_default_keybindings = 0,
    bindings = nil,
    open = false,
    side = "left",
    initial_width = 50,
    hide_statusline = false,
    update_interval = 1000,
    sections = {
      "git",
      "diagnostics",
      "files",
      "containers",
      "todos",
    },
    section_separator = {"", "-----", ""},
    section_title_separator = {""},
    containers = {
        attach_shell = "/bin/sh", show_all = true, interval = 5000,
    },
    datetime = { format = "%a %b %d, %H:%M", clocks = { { name = "local" } } },
    todos = { ignored_paths = { "~" } },
    files = {
      icon = "ï»",
      show_hidden = false,
      ignored_paths = {"%.git$"}
    },
})
EOF

nnoremap <A-s> <Cmd>SidebarNvimToggle<CR>
'''
